apiVersion: "2021-10-01"
location: westeurope
name: spark-serverless-group
type: Microsoft.ContainerInstance/containerGroups
properties:
  osType: Linux
  ipAddress:
    type: Public
    ports:
      - protocol: TCP
        port: 443
  imageRegistryCredentials:
    - server: ACR_SERVER_PLACEHOLDER
      username: ACR_USER_PLACEHOLDER
      password: ACR_PASS_PLACEHOLDER
  containers:
    - name: nginx-secure-proxy
      properties:
        image: ghcr.io/nginxinc/nginx-unprivileged:1.25-alpine
        resources:
          requests:
            cpu: 0.5
            memoryInGB: 0.5
        ports:
          - port: 443
            protocol: TCP
        command:
          - nginx
          - -g
          - "daemon off;"
          - -c
          - /etc/nginx-config/nginx.conf
        volumeMounts:
          - name: nginx-config-vol
            mountPath: /etc/nginx-config
          - name: certs-vol
            mountPath: /etc/nginx/certs
    - name: spark-iceberg-core
      properties:
        image: ACR_IMAGE_PLACEHOLDER
        resources:
          requests:
            cpu: 1.5
            memoryInGB: 2.0
        environmentVariables:
          - name: SPARK_DEFAULTS_CONF
            value: '["spark.sql.catalog.sandbox=org.apache.iceberg.spark.SparkCatalog","spark.sql.catalog.sandbox.type=hadoop","spark.sql.catalog.sandbox.warehouse=abfss://YOUR_BLOB_CONTAINER@YOUR_STORAGE_ACCOUNT.dfs.core.windows.net/warehouse","spark.hadoop.fs.azure.account.key.YOUR_STORAGE_ACCOUNT.dfs.core.windows.net=YOUR_STORAGE_ACCESS_KEY"]'
  volumes:
    - name: nginx-config-vol
      secret:
        nginx.conf: BASE64_NGINX_CONF
    - name: certs-vol
      secret:
        ca.pem: BASE64_CA_PEM
        server-cert.pem: BASE64_SERVER_CERT
        server-key.pem: BASE64_SERVER_KEY
